spring.application.name=SystemeReservation

# ========================================
# CONFIGURATION BASE DE DONNÉES (SUPABASE)
# ========================================

spring.datasource.url=jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.ihkhinprllguicmvhqvp
spring.datasource.password=poHaumzNePUzXkDh
spring.datasource.driver-class-name=org.postgresql.Driver
# ========================================
# CONFIGURATION JPA / HIBERNATE (POSTGRESQL)
# ========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Note : Le dialecte PostgreSQL est détecté automatiquement par Hibernate 6 (ligne supprimée)

# ========================================
# CONFIGURATION MAIL (GMAIL)
# ========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=landryyankam999@gmail.com
spring.mail.password=sgun eflv fdlu zxth

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ========================================
# CONFIGURATION SÉCURITÉ & JWT
# ========================================
jwt.secret=SystemeReservationTicketSecretKey2026AvecUneLongueurSecurisee123456
jwt.expiration=86400000

# ========================================
# CONFIGURATION FICHIERS & UPLOAD
# ========================================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ========================================
# LOGS & DEBUG (Allégés pour un démarrage rapide sur Render)
# ========================================
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
spring.jackson.serialization.fail-on-empty-beans=false

# ========================================
# DIVERS / SERVEUR
# ========================================
frontend.url=http://localhost:4200
server.port=${PORT:10000}